# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "ubuntu/focal64"
NUM_WORKER_NODES = 1
IP_NW = "10.0.0."
IP_START = 10

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE   # Box settings
  config.vm.provider "virtualbox" do |vb| # Provider settings
    vb.memory = 4096
    vb.cpus =1
  end
  

  (1..NUM_WORKER_NODES).each do |i|
    config.vm.define "node-0#{i}" do |node|
      node.vm.hostname = "node-0#{i}"
      # node.vm.synced_folder "./html#{i}", "/var/www/html" # Folder settings
      node.vm.network :private_network, ip: IP_NW + "#{IP_START + i}" # Network settings
      # node.vm.provision "shell", path: "./scripts/webserver.sh" # Provision settings
      # node.vm.provision "shell", path: "./scripts/database.sh"
    end
  end
end
