BOX_IMAGE = "ubuntu/bionic64"
NUM_WORKER_NODES = 2
IP_NW = "192.168.56."
IP_START = 10

Vagrant.configure("2") do |config|
	@@ -18,6 +18,7 @@ Vagrant.configure("2") do |config|
      worker.vm.hostname = "worker-0#{i}"
      worker.vm.network :private_network, ip: IP_NW + "#{IP_START + i}"
      worker.vm.provision "shell", path: "./scripts/webserver.sh"
      worker.vm.provision "shell", path: "./scripts/database.sh"
    end
  end
end