# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "ubuntu/focal64"
NUM_WORKER_NODES = 2
IP_NW = "10.0.0."
IP_START = 10

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 2
  end

  (1..NUM_WORKER_NODES).each do |i|
    config.vm.define "node-0#{i}" do |node|
      node.vm.hostname = "node-0#{i}"
      node.vm.network :private_network, ip: IP_NW + "#{IP_START + i}"
    end
  end
end
